### ISSUE TITLE
fluent ci hello world Invalid URL

### ISSUE THREAD

**Issue by dzirg44** [fluentci-io/fluentci#70]
I have the issue when I run a hello world example

<details><summary>Details</summary>

```sh
fluentci run --wasm base hello World!
✔ Pkgx setup complete
thread 'main' panicked at crates/cli/src/cmd/call.rs:140:10:
called `Result::unwrap()` on an `Err` value: expected `(`
     --> <anon>:1:1
      |
    1 | Invalid URL. The URL structure is /gh/user/repo@version/file.js
      | ^

Stack backtrace:
   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
   1: wasmtime::compile::code_builder::CodeBuilder::wasm_binary
   2: wasmtime::compile::runtime::<impl wasmtime::compile::code_builder::CodeBuilder>::compile_module
   3: wasmtime::runtime::module::Module::new
   4: extism::manifest::to_module
   5: extism::manifest::modules
   6: extism::manifest::load
   7: extism::plugin::Plugin::build_new
   8: extism::plugin_builder::PluginBuilder::build
   9: fluentci_engine::cmd::call::call
  10: tokio::runtime::park::CachedParkThread::block_on
  11: tokio::runtime::runtime::Runtime::block_on
  12: fluentci_engine::main
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: std::rt::lang_start::{{closure}}
  15: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
  16: std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  17: std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  18: std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  19: std::rt::lang_start_internal::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
  20: std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  21: std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  22: std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  23: std::rt::lang_start_internal
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  24: main
  25: __libc_start_call_main
  26: __libc_start_main@GLIBC_2.2.5
  27: _start
stack backtrace:
   0:     0x55609be72126 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x55609be72126 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55609be72126 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x55609be72126 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55609bea4970 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x55609bea4970 - core::fmt::write::h3ed6aeaa977c8e45
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x55609be6c71f - std::io::Write::write_fmt::h78b18af5775fedb5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x55609be71f04 - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55609be71f04 - std::sys_common::backtrace::print::h85035a511aafe7a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55609be73917 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
  10:     0x55609be73679 - std::panicking::default_hook::hf5fcb0f213fe709a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x55609be73da8 - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:779:13
  12:     0x55609be73c82 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
  13:     0x55609be72626 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x55609be739e0 - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  15:     0x556099b314a5 - core::panicking::panic_fmt::h784f20a50eaab275
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  16:     0x556099b319f3 - core::result::unwrap_failed::h03d8a5018196e1cd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
  17:     0x556099f5d4a1 - fluentci_engine::cmd::call::call::h2361a01aecae256c
  18:     0x556099d88c1e - tokio::runtime::park::CachedParkThread::block_on::h977ef00d9632943a
  19:     0x556099d8ab4b - tokio::runtime::runtime::Runtime::block_on::h31e95e7070ea580b
  20:     0x556099e7f4ea - fluentci_engine::main::h194fbe2b33bcb6e0
  21:     0x556099f44ba3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hdbcd2f6e60aed81a
  22:     0x556099e72a9d - std::rt::lang_start::{{closure}}::hdb70da2f2aff0319
  23:     0x55609be62271 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h37600b1e5eea4ecd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
  24:     0x55609be62271 - std::panicking::try::do_call::hb4bda49fa13a0c2b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  25:     0x55609be62271 - std::panicking::try::h8bbf75149211aaaa
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  26:     0x55609be62271 - std::panic::catch_unwind::h8c78ec68ebea34cb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  27:     0x55609be62271 - std::rt::lang_start_internal::{{closure}}::hffdf44a19fd9e220
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
  28:     0x55609be62271 - std::panicking::try::do_call::hcb3194972c74716d
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  29:     0x55609be62271 - std::panicking::try::hcdc6892c5f0dba4c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  30:     0x55609be62271 - std::panic::catch_unwind::h4910beb4573f4776
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  31:     0x55609be62271 - std::rt::lang_start_internal::h6939038e2873596b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  32:     0x556099e7f5c5 - main
  33:     0x7fef5eb96248 - __libc_start_call_main
  34:     0x7fef5eb9630b - __libc_start_main@GLIBC_2.2.5
  35:     0x556099b31cfa - _start
  36:                0x0 - <unknown>
```
</details> 

Checked some similar issues but haven't found anything helpful 

- linux x86_64
- fedora41

Even tried to disable in a sandbox selinux (for wasm I think it is not necessary, but who knows) - no luck ((

**Comment by tsirysndr** [comment]
Hi @dzirg44 ,

Thank you for bringing this to my attention!

The issue you're encountering is likely due to an older version of the module being cached. I've just published the latest version of the module, which should resolve this issue.

**Steps to Fix**:
1. Clear your FluentCI cache to ensure you're using the latest version:

```bash
rm ~/.fluentci/cache/*.wasm
```

2. Run the example again.

This will force FluentCI to download the updated module and should resolve the problem. Let me know if you continue to experience issues after trying these steps.

Thanks for your patience and for using FluentCI!

**Comment by dzirg44** [comment]
Hey, indeed , the issue has been solved) Thank you for the great tool!!! 
```sh
fluentci run --wasm base hello World!
✔ Pkgx setup complete
[exec] e82c1f28-ccfc-4dd8-b4aa-9f36ee85d52f
[exec] echo Hello World!
   Finished echo Hello World! in 0s
[hello] 83c66ffa-ff83-45b3-aef4-4938c3abf697
[hello] 
Hello World!
```
